/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kevin' at '19/08/15 09:34' with Gradle 2.4
 *
 * @author kevin, @date 19/08/15 09:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
