# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftCocoaPods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftCocoaPods

  target 'SwiftCocoaPodsTests' do
    inherit! :search_paths
    pod 'Firebase'
    pod 'Alamofire'
    pod 'Bolts-Swift'
  end

end
