/*
 * Created by IntelliJ IDEA.
 * User: Kevin Jones
 * Date: 17-Jun-02
 * Time: 17:18:04
 * To change template for new class use 
 * Code Style | Class Templates options (Tools | IDE Options).
 */
package com.mantiso.kevinj.http.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class InitDialog extends JDialog
{

    public InitDialog() throws HeadlessException
    {
        this(null, "Set Initialization Properties", false);
    }

    public InitDialog(Frame owner, String title, boolean modal) throws HeadlessException
    {
        super(owner, title, modal);
        initComponents();
    }

    protected JRootPane createRootPane()
    {
        JRootPane pane = new JRootPane();
        KeyStroke keyStroke = KeyStroke.getKeyStroke("ESCAPE");
        Action actionListener = new AbstractAction()
        {
            public void actionPerformed(ActionEvent e)
            {
                setVisible(false);
            }
        };
        InputMap inputMap = pane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(keyStroke, "ESCAPE");
        pane.getActionMap().put("ESCAPE", actionListener);
        return pane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainPanel = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        listenLabel = new javax.swing.JLabel();
        serverLabel = new javax.swing.JLabel();
        sendLabel = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        server = new javax.swing.JTextField();
        listenPort = new javax.swing.JTextField();
        sendPort = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.setMinimumSize(new java.awt.Dimension(300, 132));
        mainPanel.setPreferredSize(new java.awt.Dimension(300, 132));

        textPanel.setLayout(new java.awt.BorderLayout());

        listenLabel.setText("Listen Port");
        listenLabel.setToolTipText("Add Listen Port");
        listenLabel.setMaximumSize(new java.awt.Dimension(70, 32));
        listenLabel.setMinimumSize(new java.awt.Dimension(70, 32));
        listenLabel.setPreferredSize(new java.awt.Dimension(70, 32));
        listenLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textPanel.add(listenLabel, java.awt.BorderLayout.NORTH);

        serverLabel.setText("Server ");
        serverLabel.setToolTipText("Remote Computer to Connect To");
        serverLabel.setMaximumSize(new java.awt.Dimension(70, 32));
        serverLabel.setMinimumSize(new java.awt.Dimension(70, 32));
        serverLabel.setPreferredSize(new java.awt.Dimension(70, 32));
        textPanel.add(serverLabel, java.awt.BorderLayout.CENTER);

        sendLabel.setText("Send Port");
        sendLabel.setToolTipText("Port on Remote Computer to Connect to");
        sendLabel.setMaximumSize(new java.awt.Dimension(70, 32));
        sendLabel.setMinimumSize(new java.awt.Dimension(70, 32));
        sendLabel.setPreferredSize(new java.awt.Dimension(70, 32));
        textPanel.add(sendLabel, java.awt.BorderLayout.SOUTH);

//        getContentPane().add(textPanel, java.awt.BorderLayout.WEST);

        mainPanel.add(textPanel, java.awt.BorderLayout.WEST);
        editPanel.setLayout(new java.awt.BorderLayout());

        server.setText("localhost");
        editPanel.add(server, java.awt.BorderLayout.CENTER);

        listenPort.setText("8080");
        listenPort.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        listenPort.setMinimumSize(new java.awt.Dimension(4, 32));
        listenPort.setPreferredSize(new java.awt.Dimension(63, 32));
        editPanel.add(listenPort, java.awt.BorderLayout.NORTH);

        sendPort.setText("80");
        sendPort.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        sendPort.setMinimumSize(new java.awt.Dimension(4, 32));
        sendPort.setPreferredSize(new java.awt.Dimension(63, 32));
        editPanel.add(sendPort, java.awt.BorderLayout.SOUTH);

        mainPanel.add(editPanel, java.awt.BorderLayout.CENTER);
  //      getContentPane().add(editPanel, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        mainPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setResizable(false);
        pack();
    }//GEN-END:initComponents

    public void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        close();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void close()
    {
        setVisible(false);
        ok = false;
        dispose();
    }

    public void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Add your handling code here:
        this.setVisible(false);
        ok = true;
    }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        close();
    }//GEN-LAST:event_closeDialog


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel listenLabel;
    private javax.swing.JTextField sendPort;
    private javax.swing.JTextField listenPort;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel sendLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField server;
    // End of variables declaration//GEN-END:variables
    private boolean ok = false;

    public String getSendPort()
    {
        return sendPort.getText();
    }

    public String getListenPort()
    {
        return listenPort.getText();
    }

    public String getServer()
    {
        return server.getText();
    }

    public boolean isOk()
    {
        return ok;
    }
}
