# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TekpubData' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TekpubData

  target 'TekpubDataTests' do
    inherit! :search_paths
    pod 'FMDB'
  end

end
