//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        public int APPLICANT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public Nullable<decimal> GPA { get; set; }
        public Nullable<short> SAT_MATH_SCORE { get; set; }
        public Nullable<short> SAT_READING_SCORE { get; set; }
        public Nullable<short> SAT_WRITING_SCORE { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string TERM_CODE { get; set; }
        public string APPLICATION_STATUS { get; set; }
        public Nullable<short> POINTS { get; set; }
    
        public virtual TERM TERM { get; set; }
    }
}
