//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_STANDINGS
    {
        public CLASS_STANDINGS()
        {
            this.DEGREE_REQUIREMENTS = new HashSet<DEGREE_REQUIREMENTS>();
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public string CLASS_STANDING_CODE { get; set; }
        public string CLASS_STANDING_NAME { get; set; }
        public string DEGREE_LEVEL_CODE { get; set; }
        public short REQUIRED_CREDITS { get; set; }
    
        public virtual DEGREE_LEVELS DEGREE_LEVELS { get; set; }
        public virtual ICollection<DEGREE_REQUIREMENTS> DEGREE_REQUIREMENTS { get; set; }
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
    }
}
