//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_ENROLLMENTS
    {
        public decimal COURSE_ENROLLMENT_ID { get; set; }
        public decimal COURSE_OFFERING_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public string GRADE_CODE { get; set; }
    
        public virtual GRADE GRADE { get; set; }
        public virtual COURSE_OFFERINGS COURSE_OFFERINGS { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
