//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_OFFERINGS
    {
        public COURSE_OFFERINGS()
        {
            this.COURSE_ENROLLMENTS = new HashSet<COURSE_ENROLLMENTS>();
        }
    
        public decimal COURSE_OFFERING_ID { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public short COURSE_NUMBER { get; set; }
        public string TERM_CODE { get; set; }
        public short SECTION { get; set; }
        public short CAPACITY { get; set; }
    
        public virtual ICollection<COURSE_ENROLLMENTS> COURSE_ENROLLMENTS { get; set; }
        public virtual COURS COURS { get; set; }
        public virtual TERM TERM { get; set; }
    }
}
