//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURS
    {
        public COURS()
        {
            this.COURSE_OFFERINGS = new HashSet<COURSE_OFFERINGS>();
            this.DEGREE_REQUIREMENTS = new HashSet<DEGREE_REQUIREMENTS>();
        }
    
        public string DEPARTMENT_CODE { get; set; }
        public short COURSE_NUMBER { get; set; }
        public string COURSE_TITLE { get; set; }
        public string COURSE_DESCRIPTION { get; set; }
        public decimal CREDITS { get; set; }
        public Nullable<short> MAX_SECTION_SIZE { get; set; }
    
        public virtual ICollection<COURSE_OFFERINGS> COURSE_OFFERINGS { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<DEGREE_REQUIREMENTS> DEGREE_REQUIREMENTS { get; set; }
    }
}
