//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGREE
    {
        public DEGREE()
        {
            this.DEGREE_REQUIREMENTS = new HashSet<DEGREE_REQUIREMENTS>();
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public int DEGREE_ID { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string DEGREE_TYPE_CODE { get; set; }
        public string DEGREE_NAME { get; set; }
    
        public virtual ICollection<DEGREE_REQUIREMENTS> DEGREE_REQUIREMENTS { get; set; }
        public virtual DEGREE_TYPES DEGREE_TYPES { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
    }
}
