//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGREE_REQUIREMENTS
    {
        public int REQUIREMENT_ID { get; set; }
        public int DEGREE_ID { get; set; }
        public string CLASS_STANDING_CODE { get; set; }
        public string SESSION_CODE { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public short COURSE_NUMBER { get; set; }
    
        public virtual CLASS_STANDINGS CLASS_STANDINGS { get; set; }
        public virtual COURS COURS { get; set; }
        public virtual DEGREE DEGREE { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
