//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGREE_TYPES
    {
        public DEGREE_TYPES()
        {
            this.DEGREES = new HashSet<DEGREE>();
        }
    
        public string DEGREE_TYPE_CODE { get; set; }
        public string DEGREE_TYPE_NAME { get; set; }
        public string DEGREE_LEVEL_CODE { get; set; }
    
        public virtual DEGREE_LEVELS DEGREE_LEVELS { get; set; }
        public virtual ICollection<DEGREE> DEGREES { get; set; }
    }
}
