//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.COURSES = new HashSet<COURS>();
            this.DEGREES = new HashSet<DEGREE>();
        }
    
        public string DEPARTMENT_CODE { get; set; }
        public string DEPARTMENT_NAME { get; set; }
    
        public virtual ICollection<COURS> COURSES { get; set; }
        public virtual ICollection<DEGREE> DEGREES { get; set; }
    }
}
