//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE
    {
        public GRADE()
        {
            this.COURSE_ENROLLMENTS = new HashSet<COURSE_ENROLLMENTS>();
        }
    
        public string GRADE_CODE { get; set; }
        public Nullable<decimal> POINTS { get; set; }
        public short INCLUDE_IN_GPA { get; set; }
    
        public virtual ICollection<COURSE_ENROLLMENTS> COURSE_ENROLLMENTS { get; set; }
    }
}
