//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public SESSION()
        {
            this.DEGREE_REQUIREMENTS = new HashSet<DEGREE_REQUIREMENTS>();
            this.TERMS = new HashSet<TERM>();
        }
    
        public string SESSION_CODE { get; set; }
        public string SESSION_NAME { get; set; }
    
        public virtual ICollection<DEGREE_REQUIREMENTS> DEGREE_REQUIREMENTS { get; set; }
        public virtual ICollection<TERM> TERMS { get; set; }
    }
}
