//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.COURSE_ENROLLMENTS = new HashSet<COURSE_ENROLLMENTS>();
        }
    
        public int STUDENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public int DEGREE_PURSUED { get; set; }
        public string CLASS_STANDING_CODE { get; set; }
        public string STUDENT_STATUS { get; set; }
        public string ENROLLMENT_TERM { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string ZIP_CODE { get; set; }
    
        public virtual CLASS_STANDINGS CLASS_STANDINGS { get; set; }
        public virtual ICollection<COURSE_ENROLLMENTS> COURSE_ENROLLMENTS { get; set; }
        public virtual DEGREE DEGREE { get; set; }
        public virtual TERM TERM { get; set; }
    }
}
