//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERM
    {
        public TERM()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.COURSE_OFFERINGS = new HashSet<COURSE_OFFERINGS>();
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public string TERM_CODE { get; set; }
        public string SESSION_CODE { get; set; }
        public short YEAR { get; set; }
    
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        public virtual ICollection<COURSE_OFFERINGS> COURSE_OFFERINGS { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
    }
}
